from __future__ import annotations


def build_pre_hardware_checklist_text(metadata: dict[str, str]) -> str:
    lines = [
        "# Interface Tester Pre-Hardware Checklist",
        "",
        "## Context",
        "",
        f"- Generated: {metadata.get('generated_at', '')}",
        f"- App version: {metadata.get('app_version', '')}",
        f"- Aircraft/project: {metadata.get('aircraft', '')}",
        f"- File .dat: {metadata.get('dat_path', '')}",
        f"- Selected panel: {metadata.get('selected_panel', '')}",
        f"- Detected panel: {metadata.get('detected_panel', '')}",
        f"- Port: {metadata.get('port', '')}",
        f"- Baud rate: {metadata.get('baud_rate', '')}",
        f"- Line ending: {metadata.get('newline', '')}",
        f"- Connection: {metadata.get('connection_status', '')}",
        f"- Light type: {metadata.get('light_filter', '')}",
        f"- Output category: {metadata.get('output_filter', '')}",
        f"- Intensity: {metadata.get('intensity_mode', '')}",
        f"- Auto OFF: {metadata.get('auto_off', '')}",
        "",
        "## 1. Software and definition",
        "",
        "- [ ] Open Interface Tester and confirm the expected version.",
        "- [ ] Load the correct `.dat` file for the aircraft/project.",
        "- [ ] Review the `.dat` validation in the console or Operational Status.",
        "- [ ] Confirm that the panel/family appears only once in the table.",
        "- [ ] Open `Panel details` and review address, channel, lights, inputs, and outputs.",
        "- [ ] Review `Generated commands` before sending any command.",
        "",
        "## 2. Physical and serial connection",
        "",
        "- [ ] Connect only one panel/motherboard for this test.",
        "- [ ] Confirm power and wiring before opening the serial port.",
        "- [ ] Select the correct COM port.",
        "- [ ] Enter the correct baud rate.",
        "- [ ] Confirm the line ending expected by the board.",
        "- [ ] Press `Connect` and verify the connected status.",
        "- [ ] Send `Info` and confirm that the address/channel match the connected panel.",
        "- [ ] If `Info` is ambiguous, use `Set detected` manually.",
        "",
        "## 3. Direct Mode",
        "",
        "- [ ] Confirm that Sim Host is already downloaded before sending direct commands.",
        "- [ ] Confirm that this app does not control, start, stop, or verify Sim Host.",
        "- [ ] Confirm that no other application is using the same COM port.",
        "- [ ] Keep `Turn off when finished` enabled unless the procedure states otherwise.",
        "",
        "## 4. Light test",
        "",
        "- [ ] Start with a small test: one signal or one word when applicable.",
        "- [ ] Visually confirm ON and OFF.",
        "- [ ] If the serial response is unexpected, save the serial log before clearing it.",
        "- [ ] For a full test, use `Turn lights on`, verify, and then `Turn lights off`.",
        "- [ ] Record an `OK`, `FAIL`, or `N/A` result with a comment.",
        "",
        "## 5. VER 3 inputs",
        "",
        "- [ ] Press `Monitor VER 3` and wait for the baseline.",
        "- [ ] Move one physical control at a time.",
        "- [ ] Review the word, changed mask, signal, and logical value.",
        "- [ ] Stop monitoring before sending direct display/output commands.",
        "- [ ] Save the session if work must continue later.",
        "",
        "## 6. Displays and indicators",
        "",
        "- [ ] Review `Output details` with the correct category.",
        "- [ ] Use `Send display`, `demo`, `ST`, or `ST_Brushless` only when supported by the firmware.",
        "- [ ] Do not send manual `w` commands to non-light outputs without validating the word/bits.",
        "- [ ] Record the visual and serial responses.",
        "",
        "## 7. Minimum evidence",
        "",
        "- [ ] Save the session before changing panels.",
        "- [ ] Save the report after finishing the panel or panel group.",
        "- [ ] Save the serial log if there were errors, timeouts, or ambiguous responses.",
        "- [ ] Export Operational Status if a context snapshot is needed.",
        "- [ ] Record any procedure deviation in the panel comment.",
        "",
    ]
    return "\n".join(lines)
